### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by dantleech** [phpbench/phpbench#715]
- [ ] Finalize documentation
  - [x] Try and make all code examples executable and in CI
  - [ ] Try and make all CLI commands executable and in CI
  - [ ] Generate configuration reference
- [x] Deploy PHAR with Github actions [example for building phar](https://github.com/OskarStark/doctor-rst/blob/master/.github/workflows/build.yaml)
- [x] Make `self-update` use GH releases or remove (currently uses gh-pages which is not deployed to)
- [x] Review progress-logger API
- [ ] Show assertions in progress logger
- [x] Update reports to use expressions (?)
- [x] Introduce `--format="mode(variant.time.avg)"` and `@Format("..")` to customize the progress logger output
